# Change these first
owner: myssistant # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Dev
    url: https://dev.myssistant.com
    favicon: https://spaces.myssistant.cloud/sites/favicon-32x32.png
  - name: Dev-api
    url: https://api-dev.myssistant.com/ping
    favicon: https://spaces.myssistant.cloud/sites/favicon-32x32.png

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://spaces.myssistant.cloud/sites/android-chrome-192x192.png
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
